Fixes a bug with asynchronous metric fun evaluation
relaypro-open/imetrics pull request #26
Opened 2024-03-18 18:59 UTC by weaversam8

Values from some metrics may have been reported as belonging to other metrics. The `receive` loop now matches on pid to avoid this problem.

2024-03-18 19:21 UTC, JesseStimpson commented
This is the idiomatic way of confirming a message is meant for you.



```erlang
foo() ->
    Me = self(),
    Ref = make_ref(),
    spawn_link(fun() ->
        X = do_work(),
        Me ! {Ref, X}
    end),
    receive
         {Ref, Result} ->
             Result
    after
        1000 ->
            {error, timeout}
    end.
```

Also, don't worry about aborting the send in the timeout clause. Either the calling process will die in which case the mailbox is dropped or it will have some other way to flush itself (e.g. gen_server).

2024-03-20 20:41 UTC, JesseStimpson requested changes
Looks solid overall. Supervisor is good, install function is good, name registration is good.

2024-03-20 20:41 UTC, JesseStimpson commented on src/imetrics_vm_metrics.erl
> +handle_cast(refresh_gauges, State) ->
Let's move this to handle_info instead of handle_cast. We don't want to use the `'$gen_cast'` message structure in any code as it is an implementation detail of gen_server.

2024-03-20 20:41 UTC, JesseStimpson commented on src/imetrics_vm_metrics.erl
> +    gen_server:cast(?MODULE, refresh_gauges),
This line becomes
```erlang
self() ! refresh_gauges,
```

2024-03-20 20:57 UTC, weaversam8 commented on src/imetrics_vm_metrics.erl
> +handle_cast(refresh_gauges, State) ->
Done.

2024-03-20 20:57 UTC, weaversam8 commented on src/imetrics_vm_metrics.erl
> +    gen_server:cast(?MODULE, refresh_gauges),
Done.

2024-03-20 21:07 UTC, JesseStimpson approved these changes

2024-03-20 21:08 UTC, merged